# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        imagePullPolicy: Never # to use my local image
        resources:
          limits:
            memory: 256Mi
        command: ["sh", "-c", "echo Hello, world! && sleep infinity"]

